# Generated by Django 5.2.6 on 2026-02-03 09:21

import account.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', message='Phone number must be valid')])),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to='profile/', validators=[account.utils.validate_image])),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expired', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20, null=True)),
                ('brings', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LOVE', 'LOVE'), ('FRIENDSHIP', 'FRIENDSHIP'), ('NETWORKING', 'NETWORKING'), ('NEURODIVERSE CONNECTION', 'NEURODIVERSE CONNECTION'), ('ADVENTURE PARTNER', 'ADVENTURE PARTNER')], max_length=50, null=True)),
                ('that', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INTROVERT', 'INTROVERT'), ('EXTROVERT', 'EXTROVERT'), ('KOMBUCHA', 'KOMBUCHA'), ('CHAMPAGNE', 'CHAMPAGNE'), ('GAME OF THRONES', 'GAME OF THRONES'), ('GILMORE GIRLS', 'GILMORE GIRLS'), ('GUCCI', 'GUCCI'), ('NIKE', 'NIKE'), ('NIGHTCLUB', 'NIGHTCLUB'), ('NIGHAT AT HOME', 'NIGHT AT HOME'), ('INTUITION', 'INTUITION'), ('LOGIC', 'LOGIC'), ('BURGER', 'BURGER'), ('SALAD', 'SALAD'), ('MOUNTAIN CABIN', 'MOUNTAIN CABIN'), ('BOUTIQUE HOTEL', 'BOUTIQUE HOTEL'), ('SWEET', 'SWEET'), ('SALTY', 'SALTY'), ('DOG', 'DOG'), ('CAT', 'CAT')], max_length=50, null=True)),
                ('professional_field', models.JSONField(blank=True, default=list, null=True)),
                ('interests', models.JSONField(blank=True, default=list, null=True)),
                ('lifestyle', models.JSONField(blank=True, default=list, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('hobies', models.JSONField(blank=True, default=list, null=True)),
                ('height_feet', models.PositiveSmallIntegerField(default=0)),
                ('height_inches', models.PositiveSmallIntegerField(default=0)),
                ('dob', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MakeYourProfilePop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_pop_images/', validators=[account.utils.validate_image])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'image')},
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
