# Generated by Django 5.2.6 on 2026-02-04 04:07

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='looking_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A long-term relationship', 'A long-term relationship'), ('A life partner', 'A life partner'), ('Fun, casual dates', 'Fun, casual dates'), ('intimaIntimacy, without commitmentcy', 'Intimacy, without commitment'), ('Marriage', 'Marriage'), ('Ethical non-monogamy', 'Ethical non-monogamy')], max_length=50, null=True),
        ),
    ]
