# Generated by Django 5.2.6 on 2026-02-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userauth_location_userauth_looking_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='about',
            new_name='bio',
        ),
    ]
