# Generated by Django 5.2.6 on 2026-02-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_about_userauth_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauth',
            old_name='hobies',
            new_name='hobbies',
        ),
    ]
