# Generated by Django 5.2.6 on 2026-02-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_hobies_userauth_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
