# Generated by Django 5.2.6 on 2026-02-19 03:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userauth_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='brings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LOVE', 'LOVE'), ('FRIENDSHIP', 'FRIENDSHIP'), ('NETWORKING', 'NETWORKING'), ('NEURODIVERSE CONNECTION', 'NEURODIVERSE CONNECTION'), ('ADVENTURE PARTNER', 'ADVENTURE PARTNER')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='looking_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A long-term relationship', 'A long-term relationship'), ('A life partner', 'A life partner'), ('Fun, casual dates', 'Fun, casual dates'), ('intimaIntimacy, without commitmentcy', 'Intimacy, without commitment'), ('Marriage', 'Marriage'), ('Ethical non-monogamy', 'Ethical non-monogamy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='that',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INTROVERT', 'INTROVERT'), ('EXTROVERT', 'EXTROVERT'), ('KOMBUCHA', 'KOMBUCHA'), ('CHAMPAGNE', 'CHAMPAGNE'), ('GAME OF THRONES', 'GAME OF THRONES'), ('GILMORE GIRLS', 'GILMORE GIRLS'), ('GUCCI', 'GUCCI'), ('NIKE', 'NIKE'), ('NIGHTCLUB', 'NIGHTCLUB'), ('NIGHAT AT HOME', 'NIGHT AT HOME'), ('INTUITION', 'INTUITION'), ('LOGIC', 'LOGIC'), ('BURGER', 'BURGER'), ('SALAD', 'SALAD'), ('MOUNTAIN CABIN', 'MOUNTAIN CABIN'), ('BOUTIQUE HOTEL', 'BOUTIQUE HOTEL'), ('SWEET', 'SWEET'), ('SALTY', 'SALTY'), ('DOG', 'DOG'), ('CAT', 'CAT')], max_length=255, null=True),
        ),
    ]
