# Generated by Django 5.2.6 on 2026-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userauth_brings_alter_userauth_looking_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
