# Generated by Django 5.2.6 on 2026-02-24 04:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userauth_latitude_userauth_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326),
        ),
    ]
