# Generated by Django 5.2.6 on 2026-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userauth_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
