# Generated by Django 5.2.6 on 2026-03-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userauth_onesignal_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='onesignal_player_id',
        ),
    ]
