# Generated by Django 5.2.6 on 2026-02-16 10:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0002_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user_id', models.CharField(max_length=255)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entitlement_id', models.CharField(blank=True, max_length=255, null=True)),
                ('store', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_name', models.CharField(default='Premium Plan', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('plan_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
