# Generated by Django 5.2.6 on 2026-03-28 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('platform', models.CharField(db_index=True, max_length=20)),
                ('app_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('original_app_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('entitlement_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('is_blink_pro_active', models.BooleanField(db_index=True, default=False)),
                ('active_subscriptions', models.JSONField(blank=True, default=list)),
                ('all_purchased_product_identifiers', models.JSONField(blank=True, default=list)),
                ('all_purchase_dates', models.JSONField(blank=True, default=dict)),
                ('all_expiration_dates', models.JSONField(blank=True, default=dict)),
                ('latest_expiration_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('management_url', models.URLField(blank=True, default='', max_length=1000)),
                ('entitlements', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
