# Generated by Django 5.2.6 on 2026-02-05 05:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='stories/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4'])])),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='mutual_system.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sharer', 'shared_user')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Profile is fake', 'Profile is fake'), ('Inappropriate messages', 'Inappropriate messages'), ('Harassment or bullying', 'Harassment or bullying'), ('Offensive content', 'Offensive content'), ('Technical problem', 'Technical problem'), ('Other issues', 'Other issues')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['reported_user'], name='mutual_syst_reporte_cdac35_idx'), models.Index(fields=['reporter'], name='mutual_syst_reporte_298632_idx'), models.Index(fields=['reported_user', 'created_at'], name='mutual_syst_reporte_d114e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at', 'user'], name='mutual_syst_expires_e1ac20_idx'),
        ),
        migrations.AddIndex(
            model_name='storylike',
            index=models.Index(fields=['story', 'user'], name='mutual_syst_story_i_f68d88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storylike',
            unique_together={('story', 'user')},
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocker', 'blocked'], name='mutual_syst_blocker_84bcff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('blocker', 'blocked')},
        ),
    ]
