# Generated by Django 5.2.6 on 2026-02-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_system', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='mutual_system.story')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['story', '-created_at'], name='mutual_syst_story_i_62bd79_idx'), models.Index(fields=['viewer', '-created_at'], name='mutual_syst_viewer__ce471f_idx')],
                'constraints': [models.UniqueConstraint(fields=('story', 'viewer'), name='uniq_story_viewer')],
            },
        ),
    ]
